setwd("C:\\Users\\gassi\\Downloads\\MOOCs\\Exploratory Data Analysis\\Project1")
cons<-read.table("household_power_consumption.txt",header=TRUE,sep=";", dec=".",na.strings="?")
cons1 <- cons[cons$Date=="1/2/2007"|cons$Date=="2/2/2007",]
cons1$Global_active_power <-as.character(cons1$Global_active_power)
cons1$Global_active_power <-as.numeric(cons1$Global_active_power)
cons1$datum <- paste(cons1$Date,cons1$Time)
cons1$datum <-as.POSIXct(strptime(cons1$datum, "%d/%m/%Y %H:%M:%S"),tz="GMT")
par(mfrow = c(2, 2))
Sys.setlocale("LC_TIME", "English")
png("plot4.png",width=480, height=480, units="px",bg="white")
par(mfrow = c(2, 2))
plot(cons1$Global_active_power~cons1$datum,type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(cons1$Voltage~cons1$datum,type="l",xlab="datetime",ylab="Voltage")
with(cons1,plot(cons1$Sub_metering_1~cons1$datum,type="l",xlab="",ylab="Energy sub metering"))
lines(cons1$datum,cons1$Sub_metering_2,type="l",col="red")
lines(cons1$datum,cons1$Sub_metering_3,type="l",col="blue")
legend("topright", lty=1, col = c("black", "red","blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
plot(cons1$Global_reactive_power~cons1$datum,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()