setwd("C:\\Users\\gassi\\Downloads\\MOOCs\\Exploratory Data Analysis\\Project1")
cons<-read.table("household_power_consumption.txt",header=TRUE,sep=";", dec=".",na.strings="?")
cons1 <- cons[cons$Date=="1/2/2007"|cons$Date=="2/2/2007",]
cons1$Global_active_power <-as.character(cons1$Global_active_power)
cons1$Global_active_power <-as.numeric(cons1$Global_active_power)
cons1$datum <- paste(cons1$Date,cons1$Time)
cons1$datum <-as.POSIXct(strptime(cons1$datum, "%d/%m/%Y %H:%M:%S"),tz="GMT")
#cons1$Date <-as.Date(cons1$Date, format="%d/%m/%Y")
#cons1$Date <-strptime(cons1$Date, "%d/%m/%Y", tz = "")
#cons1$Time <-as.character(cons1$Time)
#cons1$Date <-as.Date(cons1$Date, format="%d/%m/%Y")
#cons1$Time <-strptime(cons1$Time, format="%H:%M:%S")
#cons1$Time <-strptime(cons1$Time, format="%H:%M:%S")
Sys.setlocale("LC_TIME", "English")
png("plot2.png",width=480, height=480, units="px",bg="white")
plot(cons1$Global_active_power~cons1$datum,type="l",xlab="",ylab="Global Active Power (kilowatts)")
dev.off()